language: node_js
sudo: required
services:
  - mysql
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('ngudbhav') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pngudbhav
  - sudo service mysql restart
  - mysql -u root -pngudbhav --execute="DROP DATABASE IF EXISTS ug;CREATE DATABASE ug;"
  - npm install mysql
after_success:
  - mysql -u root -pngudbhav --execute="drop database ug;"
node_js:
  - "8"